version: '3.4'
services:
  weaviate:
    command:
    - --scheme
    - http
    image: semitechnologies/weaviate:1.19.0
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_USERS: 'api_testkey'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'XVMvxrzHqPu85GD2qClHn0by2cSon0kt'
      TRANSFORMERS_PASSAGE_INFERENCE_API: 'http://t2v-transformers-passage:8080'
      TRANSFORMERS_QUERY_INFERENCE_API: 'http://t2v-transformers-query:8080'
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers-passage:
    image: semitechnologies/transformers-inference:facebook-dpr-ctx_encoder-single-nq-base
    environment:
      ENABLE_CUDA: '0'
  t2v-transformers-query:
    image: semitechnologies/transformers-inference:facebook-dpr-question_encoder-single-nq-base
    environment:
      ENABLE_CUDA: '0'
