version: '3.4'
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.22.2
    volumes:
      - /var/weaviate:/var/lib/weaviate
    ports:
      - 8080:8080
    restart: on-failure:0
    environment:
      CLUSTER_HOSTNAME: 'node1'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_USERS: 'api_testkey'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: '${WEAVIATE_APIKEY}'
      ENABLE_MODULES: 'text2vec-transformers'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      TRANSFORMERS_PASSAGE_INFERENCE_API: 'http://t2v-transformers-passage:8080'
      TRANSFORMERS_QUERY_INFERENCE_API: 'http://t2v-transformers-query:8080'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      QUERY_DEFAULTS_LIMIT: 25
  t2v-transformers-passage:
    image: semitechnologies/transformers-inference:facebook-dpr-ctx_encoder-single-nq-base
    environment:
      ENABLE_CUDA: '0'
  t2v-transformers-query:
    image: semitechnologies/transformers-inference:facebook-dpr-question_encoder-single-nq-base
    environment:
      ENABLE_CUDA: '0'
  retriever:
    build:
      context: ./askem/retriever
      dockerfile: Dockerfile
    ports:
      - 4502:4502
    environment:
      WEAVIATE_URL: '${WEAVIATE_URL}'
      WEAVIATE_APIKEY: '${WEAVIATE_APIKEY}'
      WEAVIATE_CLASS_NAME: '${WEAVIATE_CLASS_NAME}'
      RETRIEVER_URL: '${RETRIEVER_URL}'
      RETRIEVER_APIKEY: '${RETRIEVER_APIKEY}'
      HYBRID_SEARCH_XDD_URL: '${HYBRID_SEARCH_XDD_URL}'
      OPENAI_API_KEY: '${OPENAI_API_KEY}'
      OPENAI_ORGANIZATION: '${OPENAI_ORGANIZATION}'
  demo:
    build:
      context: ./askem/demo
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    environment:
      OPENAI_API_KEY: '${OPENAI_API_KEY}'
      OPENAI_ORGANIZATION: '${OPENAI_ORGANIZATION}'
      RETRIEVER_URL: '${RETRIEVER_URL}'
      RETRIEVER_APIKEY: '${RETRIEVER_APIKEY}'
      COSMOS_URL: '${COSMOS_URL}'
      DEMO_SALT: '${DEMO_SALT}'
      DEMO_HASHED_PASSWORD: '${DEMO_HASHED_PASSWORD}'
      DEBUG: 1
