version: '3.4'
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.19.0
    volumes:
      - /var/weaviate:/var/lib/weaviate
    ports:
      - 8080:8080
    restart: on-failure:0
    environment:
      CLUSTER_HOSTNAME: 'node1'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_USERS: 'api_testkey'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: '${WEAVIATE_APIKEY}'
      ENABLE_MODULES: 'text2vec-transformers'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      TRANSFORMERS_PASSAGE_INFERENCE_API: 'http://t2v-transformers-passage:8080'
      TRANSFORMERS_QUERY_INFERENCE_API: 'http://t2v-transformers-query:8080'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      QUERY_DEFAULTS_LIMIT: 25
  t2v-transformers-passage:
    image: semitechnologies/transformers-inference:facebook-dpr-ctx_encoder-single-nq-base
    environment:
      ENABLE_CUDA: '0'
  t2v-transformers-query:
    image: semitechnologies/transformers-inference:facebook-dpr-question_encoder-single-nq-base
    environment:
      ENABLE_CUDA: '0'
  generator:  # this is fully self-contained, no need to access the base askem library
    build:
      context: ./askem/generator
      dockerfile: Dockerfile
    ports:
      - 4503:4503
    environment:
      ENABLE_CUDA: '0'
      CUDA_CORE: '3'
  demo:
    build:
      dockerfile: ./askem/demo/Dockerfile
    ports:
      - 8501:8501
    environment:
      OPENAI_API_KEY: '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'
      OPENAI_ORGANIZATION: 'org-KrG6Kbas9dxwNmdeKNf50qoQ'
      WEAVIATE_URL: 'http://cosmos0001.chtc.wisc.edu:8080'
      WEAVIATE_APIKEY: 'thULk8nqccgjwPvXEjrgGn6586g8Ybiy'
      GENERATOR_URL: 'http://cosmos0001.chtc.wisc.edu:4503'
      DEMO_SALT: '$2b$12$cpeqnf/d.Uo56Z3IbeHKv.'
      DEMO_HASHED_PASSWORD: '$2b$12$cpeqnf/d.Uo56Z3IbeHKv.CeOIW7WEZfwFKS/oSjpBehXNOauOunO'
      DEBUG: 1


