version: '3.9'
services:
 llm:
  image: huggingface/transformers-pytorch-deepspeed-latest-gpu
  volumes:
    - type: bind
      source: ..
      target: /askem
  tty: true
  # deploy:
  #   resources:
  #     reservations:
  #       devices:
  #         - driver: nvidia
  #           count: all
  #           capabilities: [gpu]
